on:
  pull_request:
    types:
      - 'opened'
      - 'reopened'
jobs:
  execute-scan-workflow:
    uses: threatrix/threat-agent-scan/.github/workflows/scan-repo-reusable.yaml@master
    with:
      eid: 75fb959c-e663-4474-ae52-62f0a9373c3d
      oid: 5171b51c-f902-41c5-a6d7-d66c01832e03
      app-name: threat-matrix-2
      trx-host: https://app.threatrix.io
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      THREATRIX_SERVER_API_KEY: ${{ secrets.THREATRIX_API_KEY }}
